name: Build on linux

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
      
      - name: Build
        run: |
          mvn compile -V

      - name: Run tests
        run: |
          mvn test

      - name: Build docs
        run: |
          mvn javadoc:javadoc -Dshow=private
          