name: Build and test

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '19'
      
      - name: Build
        run: |
          mvn compile -V

      - name: Run tests
        run: |
          mvn test

          
